apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitor-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/randubnikov/final-project
    targetRevision: main
    path: helm/monitor
    helm:
      valueFiles:
        - values-production.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true